#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Wed Apr 26 2023 11:46:39
#sha1: c0ff7b
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='DESKTOP-DI75JFP', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 140 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
393,design,log,
#design: #exp: Shams Experiment
#design: #dvn: number_trials,number_flashes,response_key,RT
#design: block_cnt,block_id,trial_cnt,trial_id
393,design,logged,
393,Experiment,started
409,Stimulus,presented,1
965,Keyboard,received,32,wait
966,stderr,received,'Traceback (most recent call last):'
966,stderr,received,'  File "trial_version.py", line 121, in <module>'
967,stderr,received,'    for c in trials.FIXATION: # c should correspond to the fourth column (FIXATION)'
967,stderr,received,'  File "C:\\Users\\monik\\anaconda3\\envs\\expyriment\\lib\\site-packages\\pandas\\core\\generic.py", line 5487, in __getattr__'
984,stderr,received,'    return object.__getattribute__(self, name)'
985,stderr,received,"AttributeError: 'DataFrame' object has no attribute 'FIXATION'"
